---
creation_rules:
        - path_regex: hosts/.+/secrets.(yaml)$
          kms: 'arn:aws:kms:us-east-2:300851077188:key/b797e748-1c53-462c-9c4c-50eebebc3130'
        - path_regex: hosts/nord/syncthing/(key|cert).(pem)$
          kms: 'arn:aws:kms:us-east-2:300851077188:key/b797e748-1c53-462c-9c4c-50eebebc3130'
