# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/59e46c8b-be36-48fb-a63b-7fbef79c848a";
    fsType = "ext4";
  };

  fileSystems."/home/kat/idontcare" = {
    device = "/dev/disk/by-uuid/5fff62be-4084-4cde-b810-c7c58519d65f";
    fsType = "ext4";
    options = [
      # "uid=kat"
      # "gid=users"
      # "mode=775"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/069A-0529";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/97109afd-426e-4c3d-8804-96657a310cf9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
