# services:
  # minio:
  #   hostname: minio
  #   container_name: minio
  #   image: quay.io/minio/minio:RELEASE.2024-08-29T01-40-52Z
  #   command: server --console-address ":9001" /data
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   healthcheck:
  #     test: ["CMD", "mc", "ready", "local"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - /WD-RD0E4NHE/volsync/minio:/data

  # caddy:
  #   image: caddy:2.8.4@sha256:c6a5f2835a53fd9e2b5e0623dc7ebf0f89c163c21c05cbbc35e4ea31ff424417
  #   container_name: caddy
  #   hostname: caddy
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  #     #- ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - ./caddy/config:/config
  #     - ./caddy/data:/data
  #       #depends_on:
  #       #- minio
  #       #- ender3
  #       #- anycubic
  #       #- netbootxyz

  # https://github.com/OctoPrint/octoprint-docker/blob/master/docker-compose.yml
  #  ender3:
  #    hostname: ender3
  #    container_name: ender3
  #    image: octoprint/octoprint:1.10.2@sha256:dcc74b1a6074972ba2fce80e1abc80e98e2603adcab771918d89abaed2e4c277
  #    restart: unless-stopped
  #    ports:
  #      - "80"
  #    devices:
  #      - /dev/ttyACM0:/dev/ttyACM0
  #      - /dev/video0:/dev/video0
  #    volumes:
  #      - ./octoprint/ender3:/octoprint
  #    environment:
  #      - ENABLE_MJPG_STREAMER=true
  #
  #        #anycubic:
  #        #  hostname: anycubic
  #        #  container_name: anycubic
  #        #  image: octoprint/octoprint:1.10.2@sha256:dcc74b1a6074972ba2fce80e1abc80e98e2603adcab771918d89abaed2e4c277
  #        #  restart: unless-stopped
  #        #  ports:
  #        #    - "80"
  #        #  devices:
  #        #    - /dev/ttyACM0:/dev/ttyACM0
  #        #    - /dev/video0:/dev/video0
  #        #  volumes:
  #        #    - ./octoprint/anycubic:/octoprint
  #        #  environment:
  #        #    - ENABLE_MJPG_STREAMER=true

  # netbootxyz:
  #   image: ghcr.io/netbootxyz/netbootxyz:0.7.3-nbxyz1@sha256:8dbca4d24354fd6ace12b9970188c866341384df2925753c807e87da83587438
  #   container_name: netbootxyz
  #   hostname: netbootxyz
  #   environment:
  #     - MENU_VERSION=2.0.82 # optional
  #     - NGINX_PORT=80 # optional
  #     - WEB_APP_PORT=3000 # optional
  #   volumes:
  #     - /WD-RD0E4NHE/netbootxyz/config:/config
  #     - /WD-RD0E4NHE/netbootxyz/assets:/assets
  #   ports:
  #     - "3000"  # optional, destination should match ${WEB_APP_PORT} variable above.
  #     - 69:69/udp
  #     - "80"  # optional, destination should match ${NGINX_PORT} variable above.
  #   restart: unless-stopped