# Auto-generated using compose2nix v0.3.0.
{ pkgs, lib, ... }:

{

  # Containers
  virtualisation.oci-containers.containers."netbootxyz" = {
    image = "ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz10@sha256:e95b81cebf3af6f7223666289ff3841c607b83914a6c13a9c05fd6b7524ab190";
    environment = {
      "MENU_VERSION" = "2.0.89";
      "NGINX_PORT" = "80";
      "WEB_APP_PORT" = "3000";
    };
    volumes = [
      "/mnt/olympia/docker/netbootxyz/assets:/assets:rw"
      "/mnt/olympia/docker/netbootxyz/config:/config:rw"
    ];
    ports = [
      "127.0.0.1:3000:3000/tcp"
      "69:69/udp"
      "127.0.0.1:8088:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=netbootxyz"
      "--network-alias=netbootxyz"
      "--network=netboot_default"
    ];
  };
  systemd.services."podman-netbootxyz" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-netboot_default.service" ];
    requires = [ "podman-network-netboot_default.service" ];
    partOf = [ "podman-compose-netboot-root.target" ];
    wantedBy = [ "podman-compose-netboot-root.target" ];
    unitConfig.RequiresMountsFor = [
      "/mnt/olympia/docker/netbootxyz/config"
      "/mnt/olympia/docker/netbootxyz/assets"
    ];
  };

  # Networks
  systemd.services."podman-network-netboot_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f netboot_default";
    };
    script = ''
      podman network inspect netboot_default || podman network create netboot_default
    '';
    partOf = [ "podman-compose-netboot-root.target" ];
    wantedBy = [ "podman-compose-netboot-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-netboot-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
