add_newline = true
#prompt_order = ["username", "kubernetes", "aws", "directory", "git_branch", "git_status", "character"]

format = """\
  $username\
  $kubernetes\
  $aws\
  $directory\
  $git_branch\
  $git_status\
  $character\
  """

[aws]
format = "apf[$profile( $region)]($style) "
style = "bold Yellow"
displayed_items = "region"
#symbol = "☁️"

[aws.region_aliases]
af-south-1 = "Cape Town"
ap-east-1 = "Hong Kong"
ap-northeast-1 = "Tokyo"
ap-northeast-2 = "Seoul"
ap-northeast-3 = "Osaka"
ap-south-1 = "Mumbai"
ap-southeast-1 = "Singapore"
ap-southeast-2 = "Sydney"
ca-central-1 = "Canada"
eu-central-1 = "Frankfurt"
eu-north-1 = "Stockholm"
eu-south-1 = "Milan"
eu-west-1 = "Ireland"
eu-west-2 = "London"
eu-west-3 = "Paris"
me-south-1 = "Bahrain"
sa-east-1 = "São Paulo"
us-east-1 = "N. Virginia"
us-east-2 = "Ohio"
us-west-1 = "N. California"
us-west-2 = "Oregon"

[username]
style_root = "bold red"
style_user = "cyan bold"
show_always = true
disabled = false

[directory]
style = "bold yellow"

[kubernetes]
symbol = ""
style = "bold purple"
disabled = false
[kubernetes.context_aliases]
"production-admin@production" = "cruton-k8s"
"kubernetes-admin@kubernetes" = "cruton-dev"

[git_branch]
symbol = "⎇ "

[git_status]
conflicted = " ~ "
ahead = " ⇡ "
behind = " ⇣ "
staged = " + "
diverged = " ⇕ "
untracked = " ? "
stashed = " $ "
modified = " ! "
deleted = " 💀 "
renamed = " ➜ "
unmerged = " ═ "
