{
  name,
  nodes,
  pkgs,
  lib,
  inputs,
  ...
}:
{

  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
      MIIBlzCCAT2gAwIBAgIQUpQBQxZIqmRM7G2TXqG+6TAKBggqhkjOPQQDAjAqMSgw
      JgYDVQQDEx9oZXlqb2huLmZhbWlseSBJbnRlcm5hbCBSb290IENBMB4XDTI1MDMw
      MjA3MDE1MFoXDTM1MDIyODA3MDE1MFowKjEoMCYGA1UEAxMfaGV5am9obi5mYW1p
      bHkgSW50ZXJuYWwgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ3X
      mNYRYbLLKbGizAKZR3lYxPqnsnXmPotYokuY+vKJ8iuc7nFbSKLbl95EKR1gMY6u
      iO9zmxqsBMGff6kvb66jRTBDMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAG
      AQH/AgEBMB0GA1UdDgQWBBTlfB3jEuTS6VvJdlv7ZZxrOY4fnDAKBggqhkjOPQQD
      AgNIADBFAiEAr8RV0ixLb0c2zCQeJc1SfCRDC6rhT9xWey62p+qpmzYCIBXz63ba
      tBOU7WFC8guYTAO9xMu35MnTgYD7K0OLLGvG
      -----END CERTIFICATE-----
    ''
  ];

}
